id: P009269
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:51.899351
source_metadata:
  id: bdr:W3CN8381
  title: བོད་ཀྱི་བརྡ་སྤྲོད།
  author: ''
  volumes:
    4c59fc613c6c4cd0b115d7cb1b586ec3:
      image_group_id: I3CN8714
      title: ''
      volume_number: 1
      total_pages: 368
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
